server:
  port: "${APP_PORT}"
spring:
  application:
    name: "assets-management"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
entries:
  reactive-web:
    path-base: "${PATH_BASE}"