package com.helpcenter.model;

import lombok.Data;
import lombok.Getter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.util.Date;

@Data
@DynamoDbBean
public class AssetData {

    @Getter(onMethod_=@DynamoDbPartitionKey)
    private String assetId;
    private String assignee;
    private String acquiredAt;
    private String bill;
    private String description;
    private String status;
}
